run:
  deadline: 10m

linters:
  enable-all: false
  enable:
    # Enabled by default in golangci-lint v1.13.2
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - varcheck
    # Disabled by default in golangci-lint v1.13.2
    - dupl
    - goconst
    - gofmt
    - golint
    - unconvert
    # The following result in high memory usage (>1GB)
    # https://github.com/golangci/golangci-lint/issues/337
    - staticcheck
    - structcheck
    - gosimple
    - unused

issues:
  max-per-linter: 0
  max-same-issues: 0
