run:
  deadline: 10m

linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - gofmt
    - unconvert
    - revive
    - staticcheck
    - gosimple
    - unused

issues:
  max-per-linter: 0
  max-same-issues: 0
