{
 "title": "Victron",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Battery Charge State",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "battery_charge_percentage" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "expr": "mains_voltage_in_v" }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "expr": "mains_voltage_out_v" }
   ]
  },
  {
   "title": "Output Power",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "voltamp",
   "valueName": "current",
   "targets": [
    { "expr": "mains_power_out_va" }
   ]
  },
  {
   "title": "Output Current",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "expr": "mains_current_out_a" }
   ]
  },
  {
   "title": "Input Freq",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    { "expr": "mains_freq_in_hz" }
   ]
  },
  {
   "title": "System Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    { "expr": "mains_freq_in_hz", "legendFormat": "Input Frequency" },
    { "expr": "mains_freq_out_hz", "legendFormat": "Output Frequency" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "battery_voltage_v", "legendFormat": "Battery Voltage" }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    { "expr": "mains_power_in_va", "legendFormat": "Power In" },
    { "expr": "mains_power_out_va", "legendFormat": "Power Out" }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "mains_voltage_in_v", "legendFormat": "Input Voltage" },
    { "expr": "mains_voltage_out_v", "legendFormat": "Ouput Voltage" }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "mains_current_in_a", "legendFormat": "Input Current" },
    { "expr": "mains_current_out_a", "legendFormat": "Output Current" }
   ]
  },
  {
   "title": "Battery Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "battery_current_a", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Battery Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "battery_power_w", "legendFormat": "Battery Power" }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "battery_charge_percentage", "legendFormat": "Battery Charge" }
   ]
  }
 ]
}